package de.reichel.anlagen.model;
// Generated 25-Dec-2012 19:51:17 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UvvArt generated by hbm2java
 */
@Entity
@Table(name="UVV_ART"
    ,catalog="ansent"
)
public class UvvArt  implements java.io.Serializable {


     private UvvArtId id;

    public UvvArt() {
    }

    public UvvArt(UvvArtId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idUvvArt", column=@Column(name="ID_UVV_ART", nullable=false) ), 
        @AttributeOverride(name="timestamp", column=@Column(name="TIMESTAMP", nullable=false, length=19) ), 
        @AttributeOverride(name="idAnlagenArt", column=@Column(name="ID_ANLAGEN_ART", nullable=false) ), 
        @AttributeOverride(name="kurztext", column=@Column(name="KURZTEXT", length=50) ), 
        @AttributeOverride(name="langtext", column=@Column(name="LANGTEXT") ), 
        @AttributeOverride(name="bez1", column=@Column(name="BEZ1", length=100) ), 
        @AttributeOverride(name="bez2", column=@Column(name="BEZ2") ), 
        @AttributeOverride(name="bez3", column=@Column(name="BEZ3", length=100) ), 
        @AttributeOverride(name="bez4", column=@Column(name="BEZ4", length=100) ) } )
    public UvvArtId getId() {
        return this.id;
    }
    
    public void setId(UvvArtId id) {
        this.id = id;
    }




}


