package de.reichel.anlagen.model;
// Generated 25-Dec-2012 19:51:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Anlagen generated by hbm2java
 */
@Entity
@Table(name="ANLAGEN"
    ,catalog="ansent"
)
public class Anlagen  implements java.io.Serializable {


     private Integer idAnlagen;
     private Date timestamp;
     private Integer idAnlagenArt;
     private Integer idAnlagenHersteller;
     private String fabrikationsnummer;
     private String typ;
     private Date baujahr;
     private String interneNr;
     private String bemerkung;
     private String interneNotiz;
     private Integer idFraktion;
     private Double wartungsVertrag;
     private Date NUvv;
     private Date NWart;
     private Integer wartungsvertrag;

    public Anlagen() {
    }

    public Anlagen(Integer idAnlagenArt, Integer idAnlagenHersteller, String fabrikationsnummer, String typ, Date baujahr, String interneNr, String bemerkung, String interneNotiz, Integer idFraktion, Double wartungsVertrag, Date NUvv, Date NWart, Integer wartungsvertrag) {
       this.idAnlagenArt = idAnlagenArt;
       this.idAnlagenHersteller = idAnlagenHersteller;
       this.fabrikationsnummer = fabrikationsnummer;
       this.typ = typ;
       this.baujahr = baujahr;
       this.interneNr = interneNr;
       this.bemerkung = bemerkung;
       this.interneNotiz = interneNotiz;
       this.idFraktion = idFraktion;
       this.wartungsVertrag = wartungsVertrag;
       this.NUvv = NUvv;
       this.NWart = NWart;
       this.wartungsvertrag = wartungsvertrag;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_ANLAGEN", unique=true, nullable=false)
    public Integer getIdAnlagen() {
        return this.idAnlagen;
    }
    
    public void setIdAnlagen(Integer idAnlagen) {
        this.idAnlagen = idAnlagen;
    }
    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMP", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    
    @Column(name="ID_ANLAGEN_ART")
    public Integer getIdAnlagenArt() {
        return this.idAnlagenArt;
    }
    
    public void setIdAnlagenArt(Integer idAnlagenArt) {
        this.idAnlagenArt = idAnlagenArt;
    }
    
    @Column(name="ID_ANLAGEN_HERSTELLER")
    public Integer getIdAnlagenHersteller() {
        return this.idAnlagenHersteller;
    }
    
    public void setIdAnlagenHersteller(Integer idAnlagenHersteller) {
        this.idAnlagenHersteller = idAnlagenHersteller;
    }
    
    @Column(name="FABRIKATIONSNUMMER", length=200)
    public String getFabrikationsnummer() {
        return this.fabrikationsnummer;
    }
    
    public void setFabrikationsnummer(String fabrikationsnummer) {
        this.fabrikationsnummer = fabrikationsnummer;
    }
    
    @Column(name="TYP", length=200)
    public String getTyp() {
        return this.typ;
    }
    
    public void setTyp(String typ) {
        this.typ = typ;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BAUJAHR", length=19)
    public Date getBaujahr() {
        return this.baujahr;
    }
    
    public void setBaujahr(Date baujahr) {
        this.baujahr = baujahr;
    }
    
    @Column(name="INTERNE_NR", length=200)
    public String getInterneNr() {
        return this.interneNr;
    }
    
    public void setInterneNr(String interneNr) {
        this.interneNr = interneNr;
    }
    
    @Column(name="BEMERKUNG", length=65535)
    public String getBemerkung() {
        return this.bemerkung;
    }
    
    public void setBemerkung(String bemerkung) {
        this.bemerkung = bemerkung;
    }
    
    @Column(name="INTERNE_NOTIZ", length=65535)
    public String getInterneNotiz() {
        return this.interneNotiz;
    }
    
    public void setInterneNotiz(String interneNotiz) {
        this.interneNotiz = interneNotiz;
    }
    
    @Column(name="ID_FRAKTION")
    public Integer getIdFraktion() {
        return this.idFraktion;
    }
    
    public void setIdFraktion(Integer idFraktion) {
        this.idFraktion = idFraktion;
    }
    
    @Column(name="WARTUNGS_VERTRAG", precision=22, scale=0)
    public Double getWartungsVertrag() {
        return this.wartungsVertrag;
    }
    
    public void setWartungsVertrag(Double wartungsVertrag) {
        this.wartungsVertrag = wartungsVertrag;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="N_UVV", length=19)
    public Date getNUvv() {
        return this.NUvv;
    }
    
    public void setNUvv(Date NUvv) {
        this.NUvv = NUvv;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="N_WART", length=19)
    public Date getNWart() {
        return this.NWart;
    }
    
    public void setNWart(Date NWart) {
        this.NWart = NWart;
    }
    
    @Column(name="WARTUNGSVERTRAG")
    public Integer getWartungsvertrag() {
        return this.wartungsvertrag;
    }
    
    public void setWartungsvertrag(Integer wartungsvertrag) {
        this.wartungsvertrag = wartungsvertrag;
    }




}


