package de.reichel.anlagen.model;
// Generated 25-Dec-2012 19:51:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * AnlagenStandorte generated by hbm2java
 */
@Entity
@Table(name="ANLAGEN_STANDORTE"
    ,catalog="ansent"
)
public class AnlagenStandorte  implements java.io.Serializable {


     private Integer idAnlagenStandorte;
     private Date timestamp;
     private Integer idAnlagen;
     private Integer idStandorte;
     private Integer idBetreiber;
     private Integer idKunden;
     private Date datum;
     private Integer idUser;

    public AnlagenStandorte() {
    }

    public AnlagenStandorte(Integer idAnlagen, Integer idStandorte, Integer idBetreiber, Integer idKunden, Date datum, Integer idUser) {
       this.idAnlagen = idAnlagen;
       this.idStandorte = idStandorte;
       this.idBetreiber = idBetreiber;
       this.idKunden = idKunden;
       this.datum = datum;
       this.idUser = idUser;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_ANLAGEN_STANDORTE", unique=true, nullable=false)
    public Integer getIdAnlagenStandorte() {
        return this.idAnlagenStandorte;
    }
    
    public void setIdAnlagenStandorte(Integer idAnlagenStandorte) {
        this.idAnlagenStandorte = idAnlagenStandorte;
    }
    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMP", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    
    @Column(name="ID_ANLAGEN")
    public Integer getIdAnlagen() {
        return this.idAnlagen;
    }
    
    public void setIdAnlagen(Integer idAnlagen) {
        this.idAnlagen = idAnlagen;
    }
    
    @Column(name="ID_STANDORTE")
    public Integer getIdStandorte() {
        return this.idStandorte;
    }
    
    public void setIdStandorte(Integer idStandorte) {
        this.idStandorte = idStandorte;
    }
    
    @Column(name="ID_BETREIBER")
    public Integer getIdBetreiber() {
        return this.idBetreiber;
    }
    
    public void setIdBetreiber(Integer idBetreiber) {
        this.idBetreiber = idBetreiber;
    }
    
    @Column(name="ID_KUNDEN")
    public Integer getIdKunden() {
        return this.idKunden;
    }
    
    public void setIdKunden(Integer idKunden) {
        this.idKunden = idKunden;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATUM", length=19)
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    
    @Column(name="ID_USER")
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }




}


