package de.reichel.anlagen.model;
// Generated 25-Dec-2012 19:51:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Emails generated by hbm2java
 */
@Entity
@Table(name="EMAILS"
    ,catalog="ansent"
)
public class Emails  implements java.io.Serializable {


     private Integer idEmails;
     private Date timestamp;
     private String fromAdress;
     private String toAdress;
     private String subject;
     private String body;
     private String sentdate;
     private Date insertdate;
     private String remarks;

    public Emails() {
    }

    public Emails(String fromAdress, String toAdress, String subject, String body, String sentdate, Date insertdate, String remarks) {
       this.fromAdress = fromAdress;
       this.toAdress = toAdress;
       this.subject = subject;
       this.body = body;
       this.sentdate = sentdate;
       this.insertdate = insertdate;
       this.remarks = remarks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_EMAILS", unique=true, nullable=false)
    public Integer getIdEmails() {
        return this.idEmails;
    }
    
    public void setIdEmails(Integer idEmails) {
        this.idEmails = idEmails;
    }
    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMP", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    
    @Column(name="FROM_ADRESS")
    public String getFromAdress() {
        return this.fromAdress;
    }
    
    public void setFromAdress(String fromAdress) {
        this.fromAdress = fromAdress;
    }
    
    @Column(name="TO_ADRESS")
    public String getToAdress() {
        return this.toAdress;
    }
    
    public void setToAdress(String toAdress) {
        this.toAdress = toAdress;
    }
    
    @Column(name="SUBJECT")
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
    
    @Column(name="BODY")
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    
    @Column(name="SENTDATE")
    public String getSentdate() {
        return this.sentdate;
    }
    
    public void setSentdate(String sentdate) {
        this.sentdate = sentdate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INSERTDATE", length=19)
    public Date getInsertdate() {
        return this.insertdate;
    }
    
    public void setInsertdate(Date insertdate) {
        this.insertdate = insertdate;
    }
    
    @Column(name="REMARKS", length=65535)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


