package de.reichel.anlagen.model;
// Generated 25-Dec-2012 19:51:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * RechnungspositionenTe generated by hbm2java
 */
@Entity
@Table(name="Rechnungspositionen_TE"
    ,catalog="ansent"
)
public class RechnungspositionenTe  implements java.io.Serializable {


     private Integer id;
     private Date timestamp;
     private Integer idRechnung;
     private Short position;
     private Integer idTeile;
     private String rechnungsPosKennzeichen;
     private String bezeichnung;
     private String angebotstext;
     private Float menge;
     private String einheit;
     private Float rabatt;
     private Double preis;

    public RechnungspositionenTe() {
    }

    public RechnungspositionenTe(Integer idRechnung, Short position, Integer idTeile, String rechnungsPosKennzeichen, String bezeichnung, String angebotstext, Float menge, String einheit, Float rabatt, Double preis) {
       this.idRechnung = idRechnung;
       this.position = position;
       this.idTeile = idTeile;
       this.rechnungsPosKennzeichen = rechnungsPosKennzeichen;
       this.bezeichnung = bezeichnung;
       this.angebotstext = angebotstext;
       this.menge = menge;
       this.einheit = einheit;
       this.rabatt = rabatt;
       this.preis = preis;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMP", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    
    @Column(name="ID_RECHNUNG")
    public Integer getIdRechnung() {
        return this.idRechnung;
    }
    
    public void setIdRechnung(Integer idRechnung) {
        this.idRechnung = idRechnung;
    }
    
    @Column(name="POSITION")
    public Short getPosition() {
        return this.position;
    }
    
    public void setPosition(Short position) {
        this.position = position;
    }
    
    @Column(name="ID_TEILE")
    public Integer getIdTeile() {
        return this.idTeile;
    }
    
    public void setIdTeile(Integer idTeile) {
        this.idTeile = idTeile;
    }
    
    @Column(name="RECHNUNGS_POS_KENNZEICHEN", length=15)
    public String getRechnungsPosKennzeichen() {
        return this.rechnungsPosKennzeichen;
    }
    
    public void setRechnungsPosKennzeichen(String rechnungsPosKennzeichen) {
        this.rechnungsPosKennzeichen = rechnungsPosKennzeichen;
    }
    
    @Column(name="BEZEICHNUNG", length=65535)
    public String getBezeichnung() {
        return this.bezeichnung;
    }
    
    public void setBezeichnung(String bezeichnung) {
        this.bezeichnung = bezeichnung;
    }
    
    @Column(name="ANGEBOTSTEXT", length=65535)
    public String getAngebotstext() {
        return this.angebotstext;
    }
    
    public void setAngebotstext(String angebotstext) {
        this.angebotstext = angebotstext;
    }
    
    @Column(name="MENGE", precision=12, scale=0)
    public Float getMenge() {
        return this.menge;
    }
    
    public void setMenge(Float menge) {
        this.menge = menge;
    }
    
    @Column(name="EINHEIT", length=50)
    public String getEinheit() {
        return this.einheit;
    }
    
    public void setEinheit(String einheit) {
        this.einheit = einheit;
    }
    
    @Column(name="RABATT", precision=12, scale=0)
    public Float getRabatt() {
        return this.rabatt;
    }
    
    public void setRabatt(Float rabatt) {
        this.rabatt = rabatt;
    }
    
    @Column(name="PREIS", precision=22, scale=0)
    public Double getPreis() {
        return this.preis;
    }
    
    public void setPreis(Double preis) {
        this.preis = preis;
    }




}


