package de.reichel.anlagen.model;
// Generated 25-Dec-2012 19:51:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Saetze generated by hbm2java
 */
@Entity
@Table(name="SAETZE"
    ,catalog="ansent"
)
public class Saetze  implements java.io.Serializable {


     private int idSatz;
     private Date timestamp;
     private Integer idKunden;
     private Date gueltigBis;
     private String satzBezeichnung;
     private Double arbeitszeit;
     private Double fahrzeit;
     private Double fahrzeitHelfer;
     private Double arbzeitHelfer;
     private Double ausloese;
     private Double ueberzeit;
     private Double kilometer;
     private Double zuschlagVerschmutzung;
     private Double ersatzteileRabatt;
     private short wartungsP;
     private double wartungsPb;
     private short uvvP;
     private double uvvPb;
     private int gesperrt;

    public Saetze() {
    }

	
    public Saetze(int idSatz, short wartungsP, double wartungsPb, short uvvP, double uvvPb, int gesperrt) {
        this.idSatz = idSatz;
        this.wartungsP = wartungsP;
        this.wartungsPb = wartungsPb;
        this.uvvP = uvvP;
        this.uvvPb = uvvPb;
        this.gesperrt = gesperrt;
    }
    public Saetze(int idSatz, Integer idKunden, Date gueltigBis, String satzBezeichnung, Double arbeitszeit, Double fahrzeit, Double fahrzeitHelfer, Double arbzeitHelfer, Double ausloese, Double ueberzeit, Double kilometer, Double zuschlagVerschmutzung, Double ersatzteileRabatt, short wartungsP, double wartungsPb, short uvvP, double uvvPb, int gesperrt) {
       this.idSatz = idSatz;
       this.idKunden = idKunden;
       this.gueltigBis = gueltigBis;
       this.satzBezeichnung = satzBezeichnung;
       this.arbeitszeit = arbeitszeit;
       this.fahrzeit = fahrzeit;
       this.fahrzeitHelfer = fahrzeitHelfer;
       this.arbzeitHelfer = arbzeitHelfer;
       this.ausloese = ausloese;
       this.ueberzeit = ueberzeit;
       this.kilometer = kilometer;
       this.zuschlagVerschmutzung = zuschlagVerschmutzung;
       this.ersatzteileRabatt = ersatzteileRabatt;
       this.wartungsP = wartungsP;
       this.wartungsPb = wartungsPb;
       this.uvvP = uvvP;
       this.uvvPb = uvvPb;
       this.gesperrt = gesperrt;
    }
   
     @Id 
    
    @Column(name="ID_SATZ", unique=true, nullable=false)
    public int getIdSatz() {
        return this.idSatz;
    }
    
    public void setIdSatz(int idSatz) {
        this.idSatz = idSatz;
    }
    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMP", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    
    @Column(name="ID_KUNDEN")
    public Integer getIdKunden() {
        return this.idKunden;
    }
    
    public void setIdKunden(Integer idKunden) {
        this.idKunden = idKunden;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="GUELTIG_BIS", length=19)
    public Date getGueltigBis() {
        return this.gueltigBis;
    }
    
    public void setGueltigBis(Date gueltigBis) {
        this.gueltigBis = gueltigBis;
    }
    
    @Column(name="SATZ_BEZEICHNUNG", length=50)
    public String getSatzBezeichnung() {
        return this.satzBezeichnung;
    }
    
    public void setSatzBezeichnung(String satzBezeichnung) {
        this.satzBezeichnung = satzBezeichnung;
    }
    
    @Column(name="ARBEITSZEIT", precision=22, scale=0)
    public Double getArbeitszeit() {
        return this.arbeitszeit;
    }
    
    public void setArbeitszeit(Double arbeitszeit) {
        this.arbeitszeit = arbeitszeit;
    }
    
    @Column(name="FAHRZEIT", precision=22, scale=0)
    public Double getFahrzeit() {
        return this.fahrzeit;
    }
    
    public void setFahrzeit(Double fahrzeit) {
        this.fahrzeit = fahrzeit;
    }
    
    @Column(name="FAHRZEIT_HELFER", precision=22, scale=0)
    public Double getFahrzeitHelfer() {
        return this.fahrzeitHelfer;
    }
    
    public void setFahrzeitHelfer(Double fahrzeitHelfer) {
        this.fahrzeitHelfer = fahrzeitHelfer;
    }
    
    @Column(name="ARBZEIT_HELFER", precision=22, scale=0)
    public Double getArbzeitHelfer() {
        return this.arbzeitHelfer;
    }
    
    public void setArbzeitHelfer(Double arbzeitHelfer) {
        this.arbzeitHelfer = arbzeitHelfer;
    }
    
    @Column(name="AUSLOESE", precision=22, scale=0)
    public Double getAusloese() {
        return this.ausloese;
    }
    
    public void setAusloese(Double ausloese) {
        this.ausloese = ausloese;
    }
    
    @Column(name="UEBERZEIT", precision=22, scale=0)
    public Double getUeberzeit() {
        return this.ueberzeit;
    }
    
    public void setUeberzeit(Double ueberzeit) {
        this.ueberzeit = ueberzeit;
    }
    
    @Column(name="KILOMETER", precision=22, scale=0)
    public Double getKilometer() {
        return this.kilometer;
    }
    
    public void setKilometer(Double kilometer) {
        this.kilometer = kilometer;
    }
    
    @Column(name="ZUSCHLAG_VERSCHMUTZUNG", precision=22, scale=0)
    public Double getZuschlagVerschmutzung() {
        return this.zuschlagVerschmutzung;
    }
    
    public void setZuschlagVerschmutzung(Double zuschlagVerschmutzung) {
        this.zuschlagVerschmutzung = zuschlagVerschmutzung;
    }
    
    @Column(name="ERSATZTEILE_RABATT", precision=22, scale=0)
    public Double getErsatzteileRabatt() {
        return this.ersatzteileRabatt;
    }
    
    public void setErsatzteileRabatt(Double ersatzteileRabatt) {
        this.ersatzteileRabatt = ersatzteileRabatt;
    }
    
    @Column(name="WARTUNGS_P", nullable=false)
    public short getWartungsP() {
        return this.wartungsP;
    }
    
    public void setWartungsP(short wartungsP) {
        this.wartungsP = wartungsP;
    }
    
    @Column(name="WARTUNGS_PB", nullable=false, precision=22, scale=0)
    public double getWartungsPb() {
        return this.wartungsPb;
    }
    
    public void setWartungsPb(double wartungsPb) {
        this.wartungsPb = wartungsPb;
    }
    
    @Column(name="UVV_P", nullable=false)
    public short getUvvP() {
        return this.uvvP;
    }
    
    public void setUvvP(short uvvP) {
        this.uvvP = uvvP;
    }
    
    @Column(name="UVV_PB", nullable=false, precision=22, scale=0)
    public double getUvvPb() {
        return this.uvvPb;
    }
    
    public void setUvvPb(double uvvPb) {
        this.uvvPb = uvvPb;
    }
    
    @Column(name="GESPERRT", nullable=false)
    public int getGesperrt() {
        return this.gesperrt;
    }
    
    public void setGesperrt(int gesperrt) {
        this.gesperrt = gesperrt;
    }




}


