package de.reichel.anlagen.model;
// Generated 25-Dec-2012 19:51:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * TeileGruppen generated by hbm2java
 */
@Entity
@Table(name="TEILE_GRUPPEN"
    ,catalog="ansent"
)
public class TeileGruppen  implements java.io.Serializable {


     private Integer id;
     private Date timestamp;
     private int idTeile;
     private int idGruppen;

    public TeileGruppen() {
    }

    public TeileGruppen(int idTeile, int idGruppen) {
       this.idTeile = idTeile;
       this.idGruppen = idGruppen;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMP", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    
    @Column(name="ID_TEILE", nullable=false)
    public int getIdTeile() {
        return this.idTeile;
    }
    
    public void setIdTeile(int idTeile) {
        this.idTeile = idTeile;
    }
    
    @Column(name="ID_GRUPPEN", nullable=false)
    public int getIdGruppen() {
        return this.idGruppen;
    }
    
    public void setIdGruppen(int idGruppen) {
        this.idGruppen = idGruppen;
    }




}


