package de.reichel.anlagen.model;
// Generated 25-Dec-2012 19:51:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * TeileGruppe generated by hbm2java
 */
@Entity
@Table(name="TEILE_GRUPPE"
    ,catalog="ansent"
)
public class TeileGruppe  implements java.io.Serializable {


     private short id;
     private Date timestamp;
     private String beschreibung;

    public TeileGruppe() {
    }

	
    public TeileGruppe(short id) {
        this.id = id;
    }
    public TeileGruppe(short id, String beschreibung) {
       this.id = id;
       this.beschreibung = beschreibung;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false)
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMP", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    
    @Column(name="Beschreibung")
    public String getBeschreibung() {
        return this.beschreibung;
    }
    
    public void setBeschreibung(String beschreibung) {
        this.beschreibung = beschreibung;
    }




}


