package de.reichel.anlagen.model;
// Generated 25-Dec-2012 19:51:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UvvArt generated by hbm2java
 */
@Embeddable
public class UvvArt  implements java.io.Serializable {


     private int idUvvArt;
     private Date timestamp;
     private int idAnlagenArt;
     private String kurztext;
     private String langtext;
     private String bez1;
     private String bez2;
     private String bez3;
     private String bez4;

    public UvvArt() {
    }

	
    public UvvArt(int idUvvArt, Date timestamp, int idAnlagenArt) {
        this.idUvvArt = idUvvArt;
        this.timestamp = timestamp;
        this.idAnlagenArt = idAnlagenArt;
    }
    public UvvArt(int idUvvArt, Date timestamp, int idAnlagenArt, String kurztext, String langtext, String bez1, String bez2, String bez3, String bez4) {
       this.idUvvArt = idUvvArt;
       this.timestamp = timestamp;
       this.idAnlagenArt = idAnlagenArt;
       this.kurztext = kurztext;
       this.langtext = langtext;
       this.bez1 = bez1;
       this.bez2 = bez2;
       this.bez3 = bez3;
       this.bez4 = bez4;
    }
   

    @Column(name="ID_UVV_ART", nullable=false)
    public int getIdUvvArt() {
        return this.idUvvArt;
    }
    
    public void setIdUvvArt(int idUvvArt) {
        this.idUvvArt = idUvvArt;
    }

    @Column(name="TIMESTAMP", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    @Column(name="ID_ANLAGEN_ART", nullable=false)
    public int getIdAnlagenArt() {
        return this.idAnlagenArt;
    }
    
    public void setIdAnlagenArt(int idAnlagenArt) {
        this.idAnlagenArt = idAnlagenArt;
    }

    @Column(name="KURZTEXT", length=50)
    public String getKurztext() {
        return this.kurztext;
    }
    
    public void setKurztext(String kurztext) {
        this.kurztext = kurztext;
    }

    @Column(name="LANGTEXT")
    public String getLangtext() {
        return this.langtext;
    }
    
    public void setLangtext(String langtext) {
        this.langtext = langtext;
    }

    @Column(name="BEZ1", length=100)
    public String getBez1() {
        return this.bez1;
    }
    
    public void setBez1(String bez1) {
        this.bez1 = bez1;
    }

    @Column(name="BEZ2")
    public String getBez2() {
        return this.bez2;
    }
    
    public void setBez2(String bez2) {
        this.bez2 = bez2;
    }

    @Column(name="BEZ3", length=100)
    public String getBez3() {
        return this.bez3;
    }
    
    public void setBez3(String bez3) {
        this.bez3 = bez3;
    }

    @Column(name="BEZ4", length=100)
    public String getBez4() {
        return this.bez4;
    }
    
    public void setBez4(String bez4) {
        this.bez4 = bez4;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UvvArt) ) return false;
		 UvvArt castOther = ( UvvArt ) other; 
         
		 return (this.getIdUvvArt()==castOther.getIdUvvArt())
 && ( (this.getTimestamp()==castOther.getTimestamp()) || ( this.getTimestamp()!=null && castOther.getTimestamp()!=null && this.getTimestamp().equals(castOther.getTimestamp()) ) )
 && (this.getIdAnlagenArt()==castOther.getIdAnlagenArt())
 && ( (this.getKurztext()==castOther.getKurztext()) || ( this.getKurztext()!=null && castOther.getKurztext()!=null && this.getKurztext().equals(castOther.getKurztext()) ) )
 && ( (this.getLangtext()==castOther.getLangtext()) || ( this.getLangtext()!=null && castOther.getLangtext()!=null && this.getLangtext().equals(castOther.getLangtext()) ) )
 && ( (this.getBez1()==castOther.getBez1()) || ( this.getBez1()!=null && castOther.getBez1()!=null && this.getBez1().equals(castOther.getBez1()) ) )
 && ( (this.getBez2()==castOther.getBez2()) || ( this.getBez2()!=null && castOther.getBez2()!=null && this.getBez2().equals(castOther.getBez2()) ) )
 && ( (this.getBez3()==castOther.getBez3()) || ( this.getBez3()!=null && castOther.getBez3()!=null && this.getBez3().equals(castOther.getBez3()) ) )
 && ( (this.getBez4()==castOther.getBez4()) || ( this.getBez4()!=null && castOther.getBez4()!=null && this.getBez4().equals(castOther.getBez4()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUvvArt();
         result = 37 * result + ( getTimestamp() == null ? 0 : this.getTimestamp().hashCode() );
         result = 37 * result + this.getIdAnlagenArt();
         result = 37 * result + ( getKurztext() == null ? 0 : this.getKurztext().hashCode() );
         result = 37 * result + ( getLangtext() == null ? 0 : this.getLangtext().hashCode() );
         result = 37 * result + ( getBez1() == null ? 0 : this.getBez1().hashCode() );
         result = 37 * result + ( getBez2() == null ? 0 : this.getBez2().hashCode() );
         result = 37 * result + ( getBez3() == null ? 0 : this.getBez3().hashCode() );
         result = 37 * result + ( getBez4() == null ? 0 : this.getBez4().hashCode() );
         return result;
   }   


}


