package de.reichel.domain.model;
// Generated 25-Dec-2012 19:51:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * AnlagenHersteller generated by hbm2java
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name="ANLAGEN_HERSTELLER"
    ,catalog="ansent"
)
public class AnlagenHersteller  implements java.io.Serializable {


     private Integer idAnlagenHersteller;
     private Date timestamp;
     private String hersteller;

    public AnlagenHersteller() {
    }

    public AnlagenHersteller(String hersteller) {
       this.hersteller = hersteller;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_ANLAGEN_HERSTELLER", unique=true, nullable=false)
    public Integer getIdAnlagenHersteller() {
        return this.idAnlagenHersteller;
    }
    
    public void setIdAnlagenHersteller(Integer idAnlagenHersteller) {
        this.idAnlagenHersteller = idAnlagenHersteller;
    }
    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMP", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    
    @Column(name="HERSTELLER", length=200)
    public String getHersteller() {
        return this.hersteller;
    }
    
    public void setHersteller(String hersteller) {
        this.hersteller = hersteller;
    }




}


