package de.reichel.domain.model;
// Generated 25-Dec-2012 19:51:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * GsmSysteme generated by hbm2java
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name="GSM_SYSTEME"
    ,catalog="ansent"
)
public class GsmSysteme  implements java.io.Serializable {


     private Integer idGsm;
     private Date timestamp;
     private Integer idAnlagen;
     private Integer idStandorte;
     private String seriennummer;
     private String telefonnummer;
     private String emailFromAdress;
     private String telefonnummer1;
     private String emailFromAdress1;
     private String emailToAdress1;
     private String emailToAdress2;
     private String emailToAdress3;
     private String emailToAdress4;
     private String pin;
     private String pinPukSonst;
     private Date installation;
     private Date aktivEntsorger;
     private String bemerkung;

    public GsmSysteme() {
    }

    public GsmSysteme(Integer idAnlagen, Integer idStandorte, String seriennummer, String telefonnummer, String emailFromAdress, String telefonnummer1, String emailFromAdress1, String emailToAdress1, String emailToAdress2, String emailToAdress3, String emailToAdress4, String pin, String pinPukSonst, Date installation, Date aktivEntsorger, String bemerkung) {
       this.idAnlagen = idAnlagen;
       this.idStandorte = idStandorte;
       this.seriennummer = seriennummer;
       this.telefonnummer = telefonnummer;
       this.emailFromAdress = emailFromAdress;
       this.telefonnummer1 = telefonnummer1;
       this.emailFromAdress1 = emailFromAdress1;
       this.emailToAdress1 = emailToAdress1;
       this.emailToAdress2 = emailToAdress2;
       this.emailToAdress3 = emailToAdress3;
       this.emailToAdress4 = emailToAdress4;
       this.pin = pin;
       this.pinPukSonst = pinPukSonst;
       this.installation = installation;
       this.aktivEntsorger = aktivEntsorger;
       this.bemerkung = bemerkung;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_GSM", unique=true, nullable=false)
    public Integer getIdGsm() {
        return this.idGsm;
    }
    
    public void setIdGsm(Integer idGsm) {
        this.idGsm = idGsm;
    }
    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMP", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    
    @Column(name="ID_ANLAGEN")
    public Integer getIdAnlagen() {
        return this.idAnlagen;
    }
    
    public void setIdAnlagen(Integer idAnlagen) {
        this.idAnlagen = idAnlagen;
    }
    
    @Column(name="ID_STANDORTE")
    public Integer getIdStandorte() {
        return this.idStandorte;
    }
    
    public void setIdStandorte(Integer idStandorte) {
        this.idStandorte = idStandorte;
    }
    
    @Column(name="SERIENNUMMER", length=100)
    public String getSeriennummer() {
        return this.seriennummer;
    }
    
    public void setSeriennummer(String seriennummer) {
        this.seriennummer = seriennummer;
    }
    
    @Column(name="TELEFONNUMMER", length=100)
    public String getTelefonnummer() {
        return this.telefonnummer;
    }
    
    public void setTelefonnummer(String telefonnummer) {
        this.telefonnummer = telefonnummer;
    }
    
    @Column(name="EMAIL_FROM_ADRESS", length=100)
    public String getEmailFromAdress() {
        return this.emailFromAdress;
    }
    
    public void setEmailFromAdress(String emailFromAdress) {
        this.emailFromAdress = emailFromAdress;
    }
    
    @Column(name="TELEFONNUMMER_1", length=100)
    public String getTelefonnummer1() {
        return this.telefonnummer1;
    }
    
    public void setTelefonnummer1(String telefonnummer1) {
        this.telefonnummer1 = telefonnummer1;
    }
    
    @Column(name="EMAIL_FROM_ADRESS_1", length=100)
    public String getEmailFromAdress1() {
        return this.emailFromAdress1;
    }
    
    public void setEmailFromAdress1(String emailFromAdress1) {
        this.emailFromAdress1 = emailFromAdress1;
    }
    
    @Column(name="EMAIL_TO_ADRESS1", length=100)
    public String getEmailToAdress1() {
        return this.emailToAdress1;
    }
    
    public void setEmailToAdress1(String emailToAdress1) {
        this.emailToAdress1 = emailToAdress1;
    }
    
    @Column(name="EMAIL_TO_ADRESS2", length=100)
    public String getEmailToAdress2() {
        return this.emailToAdress2;
    }
    
    public void setEmailToAdress2(String emailToAdress2) {
        this.emailToAdress2 = emailToAdress2;
    }
    
    @Column(name="EMAIL_TO_ADRESS3", length=100)
    public String getEmailToAdress3() {
        return this.emailToAdress3;
    }
    
    public void setEmailToAdress3(String emailToAdress3) {
        this.emailToAdress3 = emailToAdress3;
    }
    
    @Column(name="EMAIL_TO_ADRESS4", length=100)
    public String getEmailToAdress4() {
        return this.emailToAdress4;
    }
    
    public void setEmailToAdress4(String emailToAdress4) {
        this.emailToAdress4 = emailToAdress4;
    }
    
    @Column(name="PIN", length=100)
    public String getPin() {
        return this.pin;
    }
    
    public void setPin(String pin) {
        this.pin = pin;
    }
    
    @Column(name="PIN_PUK_SONST", length=100)
    public String getPinPukSonst() {
        return this.pinPukSonst;
    }
    
    public void setPinPukSonst(String pinPukSonst) {
        this.pinPukSonst = pinPukSonst;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="INSTALLATION", length=10)
    public Date getInstallation() {
        return this.installation;
    }
    
    public void setInstallation(Date installation) {
        this.installation = installation;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="AKTIV_ENTSORGER", length=10)
    public Date getAktivEntsorger() {
        return this.aktivEntsorger;
    }
    
    public void setAktivEntsorger(Date aktivEntsorger) {
        this.aktivEntsorger = aktivEntsorger;
    }
    
    @Column(name="BEMERKUNG", length=250)
    public String getBemerkung() {
        return this.bemerkung;
    }
    
    public void setBemerkung(String bemerkung) {
        this.bemerkung = bemerkung;
    }




}


