package de.reichel.domain.model;
// Generated 25-Dec-2012 19:51:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Mailuser generated by hbm2java
 */
@Entity
@Table(name="MAILUSER"
    ,catalog="ansent"
)
public class Mailuser  implements java.io.Serializable {


     private Integer idMailuser;
     private Date timestamp;
     private String email;
     private String url;
     private String user;
     private String password;
     private int timeout;

    public Mailuser() {
    }

    public Mailuser(String email, String url, String user, String password, int timeout) {
       this.email = email;
       this.url = url;
       this.user = user;
       this.password = password;
       this.timeout = timeout;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_MAILUSER", unique=true, nullable=false)
    public Integer getIdMailuser() {
        return this.idMailuser;
    }
    
    public void setIdMailuser(Integer idMailuser) {
        this.idMailuser = idMailuser;
    }
    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMP", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    
    @Column(name="EMAIL", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="URL", nullable=false, length=50)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    
    @Column(name="USER", nullable=false, length=50)
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    
    @Column(name="PASSWORD", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="TIMEOUT", nullable=false)
    public int getTimeout() {
        return this.timeout;
    }
    
    public void setTimeout(int timeout) {
        this.timeout = timeout;
    }




}


