package de.reichel.domain.model;
// Generated 25-Dec-2012 19:51:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Standorte generated by hbm2java
 */
@Entity
@Table(name="STANDORTE"
    ,catalog="ansent"
)
public class Standorte  implements java.io.Serializable {


     private Integer idStandorte;
     private Date timestamp;
     private Integer idBetreiber;
     private Integer idEntsorger;
     private String strasseNr;
     private String plz;
     private String ort;
     private String land;
     private String besonderheiten;
     private String ansprechpartner;
     private String telefon;
     private String interneNotiz;
     private String bemerkung;
     private String standortname;
     private String fax;
     private String faxGsm;
     private Integer idEntsorgerFraktion1;
     private Integer idEntsorgerFraktion2;
     private Integer idEntsorgerFraktion3;
     private Integer idEntsorgerFraktion4;
     private String email;
     private String emailGsm;
     private Short anfahrtspauschale;
     private Double anfahrtspauschaleBetrag;
     private Short kilometerpauschale;
     private Double kilometerpauschaleBetrag;

    public Standorte() {
    }

    public Standorte(Integer idBetreiber, Integer idEntsorger, String strasseNr, String plz, String ort, String land, String besonderheiten, String ansprechpartner, String telefon, String interneNotiz, String bemerkung, String standortname, String fax, String faxGsm, Integer idEntsorgerFraktion1, Integer idEntsorgerFraktion2, Integer idEntsorgerFraktion3, Integer idEntsorgerFraktion4, String email, String emailGsm, Short anfahrtspauschale, Double anfahrtspauschaleBetrag, Short kilometerpauschale, Double kilometerpauschaleBetrag) {
       this.idBetreiber = idBetreiber;
       this.idEntsorger = idEntsorger;
       this.strasseNr = strasseNr;
       this.plz = plz;
       this.ort = ort;
       this.land = land;
       this.besonderheiten = besonderheiten;
       this.ansprechpartner = ansprechpartner;
       this.telefon = telefon;
       this.interneNotiz = interneNotiz;
       this.bemerkung = bemerkung;
       this.standortname = standortname;
       this.fax = fax;
       this.faxGsm = faxGsm;
       this.idEntsorgerFraktion1 = idEntsorgerFraktion1;
       this.idEntsorgerFraktion2 = idEntsorgerFraktion2;
       this.idEntsorgerFraktion3 = idEntsorgerFraktion3;
       this.idEntsorgerFraktion4 = idEntsorgerFraktion4;
       this.email = email;
       this.emailGsm = emailGsm;
       this.anfahrtspauschale = anfahrtspauschale;
       this.anfahrtspauschaleBetrag = anfahrtspauschaleBetrag;
       this.kilometerpauschale = kilometerpauschale;
       this.kilometerpauschaleBetrag = kilometerpauschaleBetrag;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_STANDORTE", unique=true, nullable=false)
    public Integer getIdStandorte() {
        return this.idStandorte;
    }
    
    public void setIdStandorte(Integer idStandorte) {
        this.idStandorte = idStandorte;
    }
    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMP", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    
    @Column(name="ID_BETREIBER")
    public Integer getIdBetreiber() {
        return this.idBetreiber;
    }
    
    public void setIdBetreiber(Integer idBetreiber) {
        this.idBetreiber = idBetreiber;
    }
    
    @Column(name="ID_ENTSORGER")
    public Integer getIdEntsorger() {
        return this.idEntsorger;
    }
    
    public void setIdEntsorger(Integer idEntsorger) {
        this.idEntsorger = idEntsorger;
    }
    
    @Column(name="STRASSE_NR", length=200)
    public String getStrasseNr() {
        return this.strasseNr;
    }
    
    public void setStrasseNr(String strasseNr) {
        this.strasseNr = strasseNr;
    }
    
    @Column(name="PLZ", length=200)
    public String getPlz() {
        return this.plz;
    }
    
    public void setPlz(String plz) {
        this.plz = plz;
    }
    
    @Column(name="ORT", length=200)
    public String getOrt() {
        return this.ort;
    }
    
    public void setOrt(String ort) {
        this.ort = ort;
    }
    
    @Column(name="LAND", length=200)
    public String getLand() {
        return this.land;
    }
    
    public void setLand(String land) {
        this.land = land;
    }
    
    @Column(name="BESONDERHEITEN", length=200)
    public String getBesonderheiten() {
        return this.besonderheiten;
    }
    
    public void setBesonderheiten(String besonderheiten) {
        this.besonderheiten = besonderheiten;
    }
    
    @Column(name="ANSPRECHPARTNER", length=200)
    public String getAnsprechpartner() {
        return this.ansprechpartner;
    }
    
    public void setAnsprechpartner(String ansprechpartner) {
        this.ansprechpartner = ansprechpartner;
    }
    
    @Column(name="TELEFON", length=200)
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }
    
    @Column(name="INTERNE_NOTIZ", length=40)
    public String getInterneNotiz() {
        return this.interneNotiz;
    }
    
    public void setInterneNotiz(String interneNotiz) {
        this.interneNotiz = interneNotiz;
    }
    
    @Column(name="BEMERKUNG", length=200)
    public String getBemerkung() {
        return this.bemerkung;
    }
    
    public void setBemerkung(String bemerkung) {
        this.bemerkung = bemerkung;
    }
    
    @Column(name="STANDORTNAME", length=200)
    public String getStandortname() {
        return this.standortname;
    }
    
    public void setStandortname(String standortname) {
        this.standortname = standortname;
    }
    
    @Column(name="FAX", length=200)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    
    @Column(name="FAX_GSM", length=200)
    public String getFaxGsm() {
        return this.faxGsm;
    }
    
    public void setFaxGsm(String faxGsm) {
        this.faxGsm = faxGsm;
    }
    
    @Column(name="ID_ENTSORGER_FRAKTION1")
    public Integer getIdEntsorgerFraktion1() {
        return this.idEntsorgerFraktion1;
    }
    
    public void setIdEntsorgerFraktion1(Integer idEntsorgerFraktion1) {
        this.idEntsorgerFraktion1 = idEntsorgerFraktion1;
    }
    
    @Column(name="ID_ENTSORGER_FRAKTION2")
    public Integer getIdEntsorgerFraktion2() {
        return this.idEntsorgerFraktion2;
    }
    
    public void setIdEntsorgerFraktion2(Integer idEntsorgerFraktion2) {
        this.idEntsorgerFraktion2 = idEntsorgerFraktion2;
    }
    
    @Column(name="ID_ENTSORGER_FRAKTION3")
    public Integer getIdEntsorgerFraktion3() {
        return this.idEntsorgerFraktion3;
    }
    
    public void setIdEntsorgerFraktion3(Integer idEntsorgerFraktion3) {
        this.idEntsorgerFraktion3 = idEntsorgerFraktion3;
    }
    
    @Column(name="ID_ENTSORGER_FRAKTION4")
    public Integer getIdEntsorgerFraktion4() {
        return this.idEntsorgerFraktion4;
    }
    
    public void setIdEntsorgerFraktion4(Integer idEntsorgerFraktion4) {
        this.idEntsorgerFraktion4 = idEntsorgerFraktion4;
    }
    
    @Column(name="EMAIL", length=200)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="EMAIL_GSM", length=200)
    public String getEmailGsm() {
        return this.emailGsm;
    }
    
    public void setEmailGsm(String emailGsm) {
        this.emailGsm = emailGsm;
    }
    
    @Column(name="ANFAHRTSPAUSCHALE")
    public Short getAnfahrtspauschale() {
        return this.anfahrtspauschale;
    }
    
    public void setAnfahrtspauschale(Short anfahrtspauschale) {
        this.anfahrtspauschale = anfahrtspauschale;
    }
    
    @Column(name="ANFAHRTSPAUSCHALE_BETRAG", precision=22, scale=0)
    public Double getAnfahrtspauschaleBetrag() {
        return this.anfahrtspauschaleBetrag;
    }
    
    public void setAnfahrtspauschaleBetrag(Double anfahrtspauschaleBetrag) {
        this.anfahrtspauschaleBetrag = anfahrtspauschaleBetrag;
    }
    
    @Column(name="KILOMETERPAUSCHALE")
    public Short getKilometerpauschale() {
        return this.kilometerpauschale;
    }
    
    public void setKilometerpauschale(Short kilometerpauschale) {
        this.kilometerpauschale = kilometerpauschale;
    }
    
    @Column(name="KILOMETERPAUSCHALE_BETRAG", precision=22, scale=0)
    public Double getKilometerpauschaleBetrag() {
        return this.kilometerpauschaleBetrag;
    }
    
    public void setKilometerpauschaleBetrag(Double kilometerpauschaleBetrag) {
        this.kilometerpauschaleBetrag = kilometerpauschaleBetrag;
    }




}


