package de.reichel.domain.model;
// Generated 25-Dec-2012 19:51:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Sub generated by hbm2java
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name="SUBS"
    ,catalog="ansent"
)
public class Sub  implements java.io.Serializable {


     private Integer idSub;
     private Date timestamp;
     private String subName;
     private String strasseNr;
     private String plz;
     private String ort;
     private String tel;
     private String fax;

    public Sub() {
    }

	
    public Sub(String subName) {
        this.subName = subName;
    }
    public Sub(String subName, String strasseNr, String plz, String ort, String tel, String fax) {
       this.subName = subName;
       this.strasseNr = strasseNr;
       this.plz = plz;
       this.ort = ort;
       this.tel = tel;
       this.fax = fax;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_SUB", unique=true, nullable=false)
    public Integer getIdSub() {
        return this.idSub;
    }
    
    public void setIdSub(Integer idSub) {
        this.idSub = idSub;
    }
    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMP", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    
    @Column(name="SUB_NAME", nullable=false, length=100)
    public String getSubName() {
        return this.subName;
    }
    
    public void setSubName(String subName) {
        this.subName = subName;
    }
    
    @Column(name="STRASSE_NR", length=100)
    public String getStrasseNr() {
        return this.strasseNr;
    }
    
    public void setStrasseNr(String strasseNr) {
        this.strasseNr = strasseNr;
    }
    
    @Column(name="PLZ", length=5)
    public String getPlz() {
        return this.plz;
    }
    
    public void setPlz(String plz) {
        this.plz = plz;
    }
    
    @Column(name="ORT", length=100)
    public String getOrt() {
        return this.ort;
    }
    
    public void setOrt(String ort) {
        this.ort = ort;
    }
    
    @Column(name="TEL", length=100)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    
    @Column(name="FAX", length=100)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }




}


