package de.reichel.domain.model;
// Generated 25-Dec-2012 19:51:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * UserTable generated by hbm2java
 */
@Entity
@Table(name="USER_TABLE"
    ,catalog="ansent"
)
public class UserTable  implements java.io.Serializable {


     private Integer idUser;
     private Date timestamp;
     private String user;
     private String password;
     private String vorname;
     private String nachname;
     private Integer idKunden;
     private Long userlevel;
     private String sid;
     private Date lastlogin;
     private String sms;
     private String fax;
     private String telefon;
     private String email;
     private Integer idBetreiber;
     private String bemerkung1;
     private String bemerkung2;
     private String bemerkung3;

    public UserTable() {
    }

    public UserTable(String user, String password, String vorname, String nachname, Integer idKunden, Long userlevel, String sid, Date lastlogin, String sms, String fax, String telefon, String email, Integer idBetreiber, String bemerkung1, String bemerkung2, String bemerkung3) {
       this.user = user;
       this.password = password;
       this.vorname = vorname;
       this.nachname = nachname;
       this.idKunden = idKunden;
       this.userlevel = userlevel;
       this.sid = sid;
       this.lastlogin = lastlogin;
       this.sms = sms;
       this.fax = fax;
       this.telefon = telefon;
       this.email = email;
       this.idBetreiber = idBetreiber;
       this.bemerkung1 = bemerkung1;
       this.bemerkung2 = bemerkung2;
       this.bemerkung3 = bemerkung3;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_USER", unique=true, nullable=false)
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMP", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    
    @Column(name="USER", length=16)
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    
    @Column(name="PASSWORD", length=16)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="VORNAME", length=200)
    public String getVorname() {
        return this.vorname;
    }
    
    public void setVorname(String vorname) {
        this.vorname = vorname;
    }
    
    @Column(name="NACHNAME", length=200)
    public String getNachname() {
        return this.nachname;
    }
    
    public void setNachname(String nachname) {
        this.nachname = nachname;
    }
    
    @Column(name="ID_KUNDEN")
    public Integer getIdKunden() {
        return this.idKunden;
    }
    
    public void setIdKunden(Integer idKunden) {
        this.idKunden = idKunden;
    }
    
    @Column(name="USERLEVEL")
    public Long getUserlevel() {
        return this.userlevel;
    }
    
    public void setUserlevel(Long userlevel) {
        this.userlevel = userlevel;
    }
    
    @Column(name="SID", length=32)
    public String getSid() {
        return this.sid;
    }
    
    public void setSid(String sid) {
        this.sid = sid;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTLOGIN", length=19)
    public Date getLastlogin() {
        return this.lastlogin;
    }
    
    public void setLastlogin(Date lastlogin) {
        this.lastlogin = lastlogin;
    }
    
    @Column(name="SMS", length=32)
    public String getSms() {
        return this.sms;
    }
    
    public void setSms(String sms) {
        this.sms = sms;
    }
    
    @Column(name="FAX", length=32)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    
    @Column(name="TELEFON", length=32)
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }
    
    @Column(name="EMAIL", length=32)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="ID_BETREIBER")
    public Integer getIdBetreiber() {
        return this.idBetreiber;
    }
    
    public void setIdBetreiber(Integer idBetreiber) {
        this.idBetreiber = idBetreiber;
    }
    
    @Column(name="BEMERKUNG_1", length=200)
    public String getBemerkung1() {
        return this.bemerkung1;
    }
    
    public void setBemerkung1(String bemerkung1) {
        this.bemerkung1 = bemerkung1;
    }
    
    @Column(name="BEMERKUNG_2", length=200)
    public String getBemerkung2() {
        return this.bemerkung2;
    }
    
    public void setBemerkung2(String bemerkung2) {
        this.bemerkung2 = bemerkung2;
    }
    
    @Column(name="BEMERKUNG_3", length=200)
    public String getBemerkung3() {
        return this.bemerkung3;
    }
    
    public void setBemerkung3(String bemerkung3) {
        this.bemerkung3 = bemerkung3;
    }




}


