package de.reichel.domain.model;
// Generated 25-Dec-2012 19:51:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * UvvMangel generated by hbm2java
 */
@Entity
@Table(name="UVV_MANGEL"
    ,catalog="ansent"
)
public class UvvMangel  implements java.io.Serializable {


     private Integer idUvvMangel;
     private Date timestamp;
     private Integer idUvv;
     private Integer idPunkt;
     private String text;
     private Short checked;

    public UvvMangel() {
    }

    public UvvMangel(Integer idUvv, Integer idPunkt, String text, Short checked) {
       this.idUvv = idUvv;
       this.idPunkt = idPunkt;
       this.text = text;
       this.checked = checked;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_UVV_MANGEL", unique=true, nullable=false)
    public Integer getIdUvvMangel() {
        return this.idUvvMangel;
    }
    
    public void setIdUvvMangel(Integer idUvvMangel) {
        this.idUvvMangel = idUvvMangel;
    }
    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMP", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    
    @Column(name="ID_UVV")
    public Integer getIdUvv() {
        return this.idUvv;
    }
    
    public void setIdUvv(Integer idUvv) {
        this.idUvv = idUvv;
    }
    
    @Column(name="ID_PUNKT")
    public Integer getIdPunkt() {
        return this.idPunkt;
    }
    
    public void setIdPunkt(Integer idPunkt) {
        this.idPunkt = idPunkt;
    }
    
    @Column(name="TEXT")
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    
    @Column(name="CHECKED")
    public Short getChecked() {
        return this.checked;
    }
    
    public void setChecked(Short checked) {
        this.checked = checked;
    }




}


