package de.reichel.domain.model;
// Generated 25-Dec-2012 19:51:17 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * UvvPunkte generated by hbm2java
 */
@Entity
@Table(name="UVV_PUNKTE"
    ,catalog="ansent"
)
public class UvvPunkte  implements java.io.Serializable {


     private Integer idUvvPunkte;
     private Date timestamp;
     private Integer idUvvArt;
     private Integer idUvvPunkteGruppen;
     private String punkt;
     private String kurztext;
     private String text;

    public UvvPunkte() {
    }

    public UvvPunkte(Integer idUvvArt, Integer idUvvPunkteGruppen, String punkt, String kurztext, String text) {
       this.idUvvArt = idUvvArt;
       this.idUvvPunkteGruppen = idUvvPunkteGruppen;
       this.punkt = punkt;
       this.kurztext = kurztext;
       this.text = text;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID_UVV_PUNKTE", unique=true, nullable=false)
    public Integer getIdUvvPunkte() {
        return this.idUvvPunkte;
    }
    
    public void setIdUvvPunkte(Integer idUvvPunkte) {
        this.idUvvPunkte = idUvvPunkte;
    }
    @Version@Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMP", nullable=false, length=19)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    
    @Column(name="ID_UVV_ART")
    public Integer getIdUvvArt() {
        return this.idUvvArt;
    }
    
    public void setIdUvvArt(Integer idUvvArt) {
        this.idUvvArt = idUvvArt;
    }
    
    @Column(name="ID_UVV_PUNKTE_GRUPPEN")
    public Integer getIdUvvPunkteGruppen() {
        return this.idUvvPunkteGruppen;
    }
    
    public void setIdUvvPunkteGruppen(Integer idUvvPunkteGruppen) {
        this.idUvvPunkteGruppen = idUvvPunkteGruppen;
    }
    
    @Column(name="PUNKT", length=50)
    public String getPunkt() {
        return this.punkt;
    }
    
    public void setPunkt(String punkt) {
        this.punkt = punkt;
    }
    
    @Column(name="KURZTEXT", length=50)
    public String getKurztext() {
        return this.kurztext;
    }
    
    public void setKurztext(String kurztext) {
        this.kurztext = kurztext;
    }
    
    @Column(name="TEXT")
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


